# latexmk.yml: GitHub action to ensure latex files compile.
name: CI
on: push
jobs:
  compile-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v3
      - name: Compile main.tex
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: template
          root_file: main.tex
          compiler: latexmk
          args: -pdf -g -file-line-error -interaction=nonstopmode -Werror
          post_compile: "latexmk -c"
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: template/main.pdf
